# Specify the directories on your systems

# The BIDS directory with data to be processed
datadir: 
# The directory with the Snakemake pipeline specification
rootdir: 

# The singularity containers used by the pipeline
containers:
  fmriprep: docker://nipreps/fmriprep:latest
  freesurfer: docker://freesurfer/freesurfer:7.4.1
  xcp_d: docker://pennlinc/xcp_d:latest
  wb_command: docker://vnmd/connectomeworkbench_2.0.1:latest