datadir: /home/david-daubner/Desktop/NMDARE/bids
rootdir: /home/david-daubner/Desktop/NMDARE/nmdare-processing

containers:
  fmriprep: /home/david-daubner/Desktop/NMDARE/nmdare-processing/.snakemake/singularity/fmriprep.sif
  freesurfer: /home/david-daubner/Desktop/NMDARE/nmdare-processing/.snakemake/singularity/freesurfer.sif
  xcp_d: /home/david-daubner/Desktop/NMDARE/nmdare-processing/.snakemake/singularity/xcpd.sif
  wb_command: /home/david-daubner/Desktop/NMDARE/nmdare-processing/.snakemake/singularity/wb_command.sif